### ISSUE TITLE
Dynamic lists and re-binding model to a view

### ISSUE THREAD

**Issue by qchroman** [theironcook/Backbone.ModelBinder#192]
Hello Guys,

Is there a way to tell ModelBinder not to change the value of the HTML element when I call bind()?

The problem is that If I have set some default values on HTML fields and I have called bind() and if my model's fields are blank, all of the values will disappear from the HTML fields.

**Comment by platinumazure** [comment]
@qchroman It sounds to me like you're probably not using Backbone.ModelBinder correctly if you call `bind` multiple times only after you get values back.

In this case, I think you would do better to use a CollectionBinder and ElManagerFactory to handle a collection of countries and regions. By doing that, you can set up your bindings even before fetching either of those pieces of information. (If your collections are also model attributes, then you can take advantage of ModelBinder in the containing view to disable/hide and enable/show the dropdowns depending on the lengths of the collections.)

Whenever I use this library, I think it's nearly always a code smell or design smell on my part if I think I need to apply model bindings only after a certain point. The whole point of ModelBinder is so that you can apply bindings early on and have it automatically take care of changes for you-- this includes if the values aren't there in the first place. I always try to challenge myself to apply all my bindings right when my view is rendered and no later. (Note that "applying all my bindings" is not the same as "having all my data available" here!)

If you're still stuck, you can set up a JSFiddle with a simple example and I'd be happy to look at it and try to point you in the right direction. (As a suggestion, you can mock out your server fetches by using `setTimeout` to do a collection `set` later-- that results in basically the same behavior.)

**Comment by platinumazure** [comment]
Also, as a stopgap, you could use a converter to ensure that an undefined model value is converted to an appropriate default value.

It might be worth creating a feature to allow ModelBinder to explicitly force view elements to go back to some "pre-bound" default state if the model attribute is empty, rather than forcing the view element to empty. I could see that coming in handy.

**Comment by amakhrov** [comment]
I don't think it's a problem with the existing behavior. Should we close this issue?

**Comment by qchroman** [comment]
Lest's close it for now, yes. Thank you all. Sorry, just don't have enough time to look into this right now :)
