### ISSUE TITLE
Customizing bindings for CollectionBinder

### ISSUE THREAD

**Issue by chuyler1** [theironcook/Backbone.ModelBinder#197]
Is there a way to utilize converter and attribute bindings when using CollectionBinder?  

Instead of calling...
```javascript
var elManagerFactory = new Backbone.CollectionBinder.ElManagerFactory(rowHtml, "data-name");
collectionBinder = new Backbone.CollectionBinder(elManagerFactory);
collectionBinder.bind(collection, view.$('tbody'));
```
I would like to do something like this...
```javascript
var bindings = Backbone.ModelBinder.createDefaultBindings(view.$('tbody'), "data-name"));
bindings[phoneNumber] = {selector: '[name=phoneNumber]', converter: phoneConverter}};
var elManagerFactory = new Backbone.CollectionBinder.ElManagerFactory(rowHtml, bindings);
collectionBinder = new Backbone.CollectionBinder(elManagerFactory);
collectionBinder.bind(collection, view.$('tbody'));
```
I can see that line 197 of Backbone.CollectionBinder appears to support passing in an object, but I can't get it to actually work.  In fact it just breaks all the bindings instead of adding this phone number formatter.

**Comment by platinumazure** [comment]
Hi @chuyler1, if you've figured your issue out and don't have anything you need from the maintainers, would you mind closing this issue? Otherwise, if you still have a question, please don't hesitate to ask. (If you're having trouble elsewhere, though, please do consider closing this and opening a new issue. Thanks!)
