### ISSUE TITLE
autofill form in safari 8.0

### ISSUE THREAD

**Issue by pixelatorz** [theironcook/Backbone.ModelBinder#214]
when using autofill in safari the object remains empty, I have a form binded to a user model, when you fill in the form manually it fills the user object perfectly, when using chrome autofill it does also work. 

autofill safari:
![safari](https://cloud.githubusercontent.com/assets/1567481/7412008/4f1c73c6-ef3e-11e4-92e4-4c80681b4f82.png)

autofill chrome:
![chrome](https://cloud.githubusercontent.com/assets/1567481/7412009/4f221e02-ef3e-11e4-80b1-e7073978891a.png)

**Comment by platinumazure** [comment]
I imagine this has more to do with whether Chrome or Safari emit [change events][1] when using their auto-fill features, rather than anything in Backbone.ModelBinder.

You could test this by performing the following steps:

  1. Use Safari's auto-fill to populate the form.
  2. Optionally, verify the model is still empty in Safari.
  3. Use jQuery to select all of your forms and trigger a change event. For example:
         jQuery("select, input").trigger("change");
  4. See if the model is now populated.

If the above steps populate the model, then unfortunately there's nothing we can do here. It's a bug in the auto-fill plugin for Safari.

**Comment by pixelatorz** [comment]
thats seems to be the problem indeed. 

It does work with triggering the change event, that I didn't think of that. 

thanks for the help!
